# CHATBOT/docker-compose.yml

version: '3.8' # Chỉ định phiên bản Docker Compose

services:
  chatbot-api: 
    build:
      context: . # Build image từ Dockerfile trong thư mục hiện tại (CHATBOT/)
      dockerfile: Dockerfile # Tên của Dockerfile
    container_name: chatbot_api # Tên cụ thể cho container khi chạy
    restart: unless-stopped # Tự động khởi động lại container trừ khi nó bị dừng thủ công
    ports:
      - "8888:8888" # 
    env_file:
      - .env # Đọc các biến môi trường từ file .env ở thư mục gốc CHATBOT/
    volumes:
      # Volume này dùng cho development để code thay đổi trên máy host
      # sẽ được phản ánh ngay vào container, kết hợp với --reload của Uvicorn.
      # Xóa hoặc comment dòng này cho môi trường production.
      - ./app:/app/app
    networks:
      - chatbot_network # (Tùy chọn) Sử dụng network riêng

# (Tùy chọn) Định nghĩa network
networks:
  chatbot_network:
    driver: bridge